# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['CosBucketObjectLockConfigurationArgs', 'CosBucketObjectLockConfiguration']

@pulumi.input_type
class CosBucketObjectLockConfigurationArgs:
    def __init__(__self__, *,
                 bucket_crn: pulumi.Input[_builtins.str],
                 bucket_location: pulumi.Input[_builtins.str],
                 object_lock_configuration: pulumi.Input['CosBucketObjectLockConfigurationObjectLockConfigurationArgs'],
                 cos_bucket_object_lock_configuration_id: Optional[pulumi.Input[_builtins.str]] = None,
                 endpoint_type: Optional[pulumi.Input[_builtins.str]] = None,
                 timeouts: Optional[pulumi.Input['CosBucketObjectLockConfigurationTimeoutsArgs']] = None):
        """
        The set of arguments for constructing a CosBucketObjectLockConfiguration resource.
        :param pulumi.Input[_builtins.str] bucket_crn: COS bucket CRN
        :param pulumi.Input[_builtins.str] bucket_location: COS bucket location
        :param pulumi.Input['CosBucketObjectLockConfigurationObjectLockConfigurationArgs'] object_lock_configuration: Bucket level object lock settings includes Days, Years, Mode.
        :param pulumi.Input[_builtins.str] endpoint_type: COS endpoint type: public, private, direct
        """
        pulumi.set(__self__, "bucket_crn", bucket_crn)
        pulumi.set(__self__, "bucket_location", bucket_location)
        pulumi.set(__self__, "object_lock_configuration", object_lock_configuration)
        if cos_bucket_object_lock_configuration_id is not None:
            pulumi.set(__self__, "cos_bucket_object_lock_configuration_id", cos_bucket_object_lock_configuration_id)
        if endpoint_type is not None:
            pulumi.set(__self__, "endpoint_type", endpoint_type)
        if timeouts is not None:
            pulumi.set(__self__, "timeouts", timeouts)

    @_builtins.property
    @pulumi.getter(name="bucketCrn")
    def bucket_crn(self) -> pulumi.Input[_builtins.str]:
        """
        COS bucket CRN
        """
        return pulumi.get(self, "bucket_crn")

    @bucket_crn.setter
    def bucket_crn(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "bucket_crn", value)

    @_builtins.property
    @pulumi.getter(name="bucketLocation")
    def bucket_location(self) -> pulumi.Input[_builtins.str]:
        """
        COS bucket location
        """
        return pulumi.get(self, "bucket_location")

    @bucket_location.setter
    def bucket_location(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "bucket_location", value)

    @_builtins.property
    @pulumi.getter(name="objectLockConfiguration")
    def object_lock_configuration(self) -> pulumi.Input['CosBucketObjectLockConfigurationObjectLockConfigurationArgs']:
        """
        Bucket level object lock settings includes Days, Years, Mode.
        """
        return pulumi.get(self, "object_lock_configuration")

    @object_lock_configuration.setter
    def object_lock_configuration(self, value: pulumi.Input['CosBucketObjectLockConfigurationObjectLockConfigurationArgs']):
        pulumi.set(self, "object_lock_configuration", value)

    @_builtins.property
    @pulumi.getter(name="cosBucketObjectLockConfigurationId")
    def cos_bucket_object_lock_configuration_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "cos_bucket_object_lock_configuration_id")

    @cos_bucket_object_lock_configuration_id.setter
    def cos_bucket_object_lock_configuration_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cos_bucket_object_lock_configuration_id", value)

    @_builtins.property
    @pulumi.getter(name="endpointType")
    def endpoint_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        COS endpoint type: public, private, direct
        """
        return pulumi.get(self, "endpoint_type")

    @endpoint_type.setter
    def endpoint_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "endpoint_type", value)

    @_builtins.property
    @pulumi.getter
    def timeouts(self) -> Optional[pulumi.Input['CosBucketObjectLockConfigurationTimeoutsArgs']]:
        return pulumi.get(self, "timeouts")

    @timeouts.setter
    def timeouts(self, value: Optional[pulumi.Input['CosBucketObjectLockConfigurationTimeoutsArgs']]):
        pulumi.set(self, "timeouts", value)


@pulumi.input_type
class _CosBucketObjectLockConfigurationState:
    def __init__(__self__, *,
                 bucket_crn: Optional[pulumi.Input[_builtins.str]] = None,
                 bucket_location: Optional[pulumi.Input[_builtins.str]] = None,
                 cos_bucket_object_lock_configuration_id: Optional[pulumi.Input[_builtins.str]] = None,
                 endpoint_type: Optional[pulumi.Input[_builtins.str]] = None,
                 object_lock_configuration: Optional[pulumi.Input['CosBucketObjectLockConfigurationObjectLockConfigurationArgs']] = None,
                 timeouts: Optional[pulumi.Input['CosBucketObjectLockConfigurationTimeoutsArgs']] = None):
        """
        Input properties used for looking up and filtering CosBucketObjectLockConfiguration resources.
        :param pulumi.Input[_builtins.str] bucket_crn: COS bucket CRN
        :param pulumi.Input[_builtins.str] bucket_location: COS bucket location
        :param pulumi.Input[_builtins.str] endpoint_type: COS endpoint type: public, private, direct
        :param pulumi.Input['CosBucketObjectLockConfigurationObjectLockConfigurationArgs'] object_lock_configuration: Bucket level object lock settings includes Days, Years, Mode.
        """
        if bucket_crn is not None:
            pulumi.set(__self__, "bucket_crn", bucket_crn)
        if bucket_location is not None:
            pulumi.set(__self__, "bucket_location", bucket_location)
        if cos_bucket_object_lock_configuration_id is not None:
            pulumi.set(__self__, "cos_bucket_object_lock_configuration_id", cos_bucket_object_lock_configuration_id)
        if endpoint_type is not None:
            pulumi.set(__self__, "endpoint_type", endpoint_type)
        if object_lock_configuration is not None:
            pulumi.set(__self__, "object_lock_configuration", object_lock_configuration)
        if timeouts is not None:
            pulumi.set(__self__, "timeouts", timeouts)

    @_builtins.property
    @pulumi.getter(name="bucketCrn")
    def bucket_crn(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        COS bucket CRN
        """
        return pulumi.get(self, "bucket_crn")

    @bucket_crn.setter
    def bucket_crn(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "bucket_crn", value)

    @_builtins.property
    @pulumi.getter(name="bucketLocation")
    def bucket_location(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        COS bucket location
        """
        return pulumi.get(self, "bucket_location")

    @bucket_location.setter
    def bucket_location(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "bucket_location", value)

    @_builtins.property
    @pulumi.getter(name="cosBucketObjectLockConfigurationId")
    def cos_bucket_object_lock_configuration_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "cos_bucket_object_lock_configuration_id")

    @cos_bucket_object_lock_configuration_id.setter
    def cos_bucket_object_lock_configuration_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cos_bucket_object_lock_configuration_id", value)

    @_builtins.property
    @pulumi.getter(name="endpointType")
    def endpoint_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        COS endpoint type: public, private, direct
        """
        return pulumi.get(self, "endpoint_type")

    @endpoint_type.setter
    def endpoint_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "endpoint_type", value)

    @_builtins.property
    @pulumi.getter(name="objectLockConfiguration")
    def object_lock_configuration(self) -> Optional[pulumi.Input['CosBucketObjectLockConfigurationObjectLockConfigurationArgs']]:
        """
        Bucket level object lock settings includes Days, Years, Mode.
        """
        return pulumi.get(self, "object_lock_configuration")

    @object_lock_configuration.setter
    def object_lock_configuration(self, value: Optional[pulumi.Input['CosBucketObjectLockConfigurationObjectLockConfigurationArgs']]):
        pulumi.set(self, "object_lock_configuration", value)

    @_builtins.property
    @pulumi.getter
    def timeouts(self) -> Optional[pulumi.Input['CosBucketObjectLockConfigurationTimeoutsArgs']]:
        return pulumi.get(self, "timeouts")

    @timeouts.setter
    def timeouts(self, value: Optional[pulumi.Input['CosBucketObjectLockConfigurationTimeoutsArgs']]):
        pulumi.set(self, "timeouts", value)


@pulumi.type_token("ibm:index/cosBucketObjectLockConfiguration:CosBucketObjectLockConfiguration")
class CosBucketObjectLockConfiguration(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 bucket_crn: Optional[pulumi.Input[_builtins.str]] = None,
                 bucket_location: Optional[pulumi.Input[_builtins.str]] = None,
                 cos_bucket_object_lock_configuration_id: Optional[pulumi.Input[_builtins.str]] = None,
                 endpoint_type: Optional[pulumi.Input[_builtins.str]] = None,
                 object_lock_configuration: Optional[pulumi.Input[Union['CosBucketObjectLockConfigurationObjectLockConfigurationArgs', 'CosBucketObjectLockConfigurationObjectLockConfigurationArgsDict']]] = None,
                 timeouts: Optional[pulumi.Input[Union['CosBucketObjectLockConfigurationTimeoutsArgs', 'CosBucketObjectLockConfigurationTimeoutsArgsDict']]] = None,
                 __props__=None):
        """
        Create a CosBucketObjectLockConfiguration resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] bucket_crn: COS bucket CRN
        :param pulumi.Input[_builtins.str] bucket_location: COS bucket location
        :param pulumi.Input[_builtins.str] endpoint_type: COS endpoint type: public, private, direct
        :param pulumi.Input[Union['CosBucketObjectLockConfigurationObjectLockConfigurationArgs', 'CosBucketObjectLockConfigurationObjectLockConfigurationArgsDict']] object_lock_configuration: Bucket level object lock settings includes Days, Years, Mode.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: CosBucketObjectLockConfigurationArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a CosBucketObjectLockConfiguration resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param CosBucketObjectLockConfigurationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CosBucketObjectLockConfigurationArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 bucket_crn: Optional[pulumi.Input[_builtins.str]] = None,
                 bucket_location: Optional[pulumi.Input[_builtins.str]] = None,
                 cos_bucket_object_lock_configuration_id: Optional[pulumi.Input[_builtins.str]] = None,
                 endpoint_type: Optional[pulumi.Input[_builtins.str]] = None,
                 object_lock_configuration: Optional[pulumi.Input[Union['CosBucketObjectLockConfigurationObjectLockConfigurationArgs', 'CosBucketObjectLockConfigurationObjectLockConfigurationArgsDict']]] = None,
                 timeouts: Optional[pulumi.Input[Union['CosBucketObjectLockConfigurationTimeoutsArgs', 'CosBucketObjectLockConfigurationTimeoutsArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CosBucketObjectLockConfigurationArgs.__new__(CosBucketObjectLockConfigurationArgs)

            if bucket_crn is None and not opts.urn:
                raise TypeError("Missing required property 'bucket_crn'")
            __props__.__dict__["bucket_crn"] = bucket_crn
            if bucket_location is None and not opts.urn:
                raise TypeError("Missing required property 'bucket_location'")
            __props__.__dict__["bucket_location"] = bucket_location
            __props__.__dict__["cos_bucket_object_lock_configuration_id"] = cos_bucket_object_lock_configuration_id
            __props__.__dict__["endpoint_type"] = endpoint_type
            if object_lock_configuration is None and not opts.urn:
                raise TypeError("Missing required property 'object_lock_configuration'")
            __props__.__dict__["object_lock_configuration"] = object_lock_configuration
            __props__.__dict__["timeouts"] = timeouts
        super(CosBucketObjectLockConfiguration, __self__).__init__(
            'ibm:index/cosBucketObjectLockConfiguration:CosBucketObjectLockConfiguration',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            bucket_crn: Optional[pulumi.Input[_builtins.str]] = None,
            bucket_location: Optional[pulumi.Input[_builtins.str]] = None,
            cos_bucket_object_lock_configuration_id: Optional[pulumi.Input[_builtins.str]] = None,
            endpoint_type: Optional[pulumi.Input[_builtins.str]] = None,
            object_lock_configuration: Optional[pulumi.Input[Union['CosBucketObjectLockConfigurationObjectLockConfigurationArgs', 'CosBucketObjectLockConfigurationObjectLockConfigurationArgsDict']]] = None,
            timeouts: Optional[pulumi.Input[Union['CosBucketObjectLockConfigurationTimeoutsArgs', 'CosBucketObjectLockConfigurationTimeoutsArgsDict']]] = None) -> 'CosBucketObjectLockConfiguration':
        """
        Get an existing CosBucketObjectLockConfiguration resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] bucket_crn: COS bucket CRN
        :param pulumi.Input[_builtins.str] bucket_location: COS bucket location
        :param pulumi.Input[_builtins.str] endpoint_type: COS endpoint type: public, private, direct
        :param pulumi.Input[Union['CosBucketObjectLockConfigurationObjectLockConfigurationArgs', 'CosBucketObjectLockConfigurationObjectLockConfigurationArgsDict']] object_lock_configuration: Bucket level object lock settings includes Days, Years, Mode.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _CosBucketObjectLockConfigurationState.__new__(_CosBucketObjectLockConfigurationState)

        __props__.__dict__["bucket_crn"] = bucket_crn
        __props__.__dict__["bucket_location"] = bucket_location
        __props__.__dict__["cos_bucket_object_lock_configuration_id"] = cos_bucket_object_lock_configuration_id
        __props__.__dict__["endpoint_type"] = endpoint_type
        __props__.__dict__["object_lock_configuration"] = object_lock_configuration
        __props__.__dict__["timeouts"] = timeouts
        return CosBucketObjectLockConfiguration(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="bucketCrn")
    def bucket_crn(self) -> pulumi.Output[_builtins.str]:
        """
        COS bucket CRN
        """
        return pulumi.get(self, "bucket_crn")

    @_builtins.property
    @pulumi.getter(name="bucketLocation")
    def bucket_location(self) -> pulumi.Output[_builtins.str]:
        """
        COS bucket location
        """
        return pulumi.get(self, "bucket_location")

    @_builtins.property
    @pulumi.getter(name="cosBucketObjectLockConfigurationId")
    def cos_bucket_object_lock_configuration_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "cos_bucket_object_lock_configuration_id")

    @_builtins.property
    @pulumi.getter(name="endpointType")
    def endpoint_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        COS endpoint type: public, private, direct
        """
        return pulumi.get(self, "endpoint_type")

    @_builtins.property
    @pulumi.getter(name="objectLockConfiguration")
    def object_lock_configuration(self) -> pulumi.Output['outputs.CosBucketObjectLockConfigurationObjectLockConfiguration']:
        """
        Bucket level object lock settings includes Days, Years, Mode.
        """
        return pulumi.get(self, "object_lock_configuration")

    @_builtins.property
    @pulumi.getter
    def timeouts(self) -> pulumi.Output[Optional['outputs.CosBucketObjectLockConfigurationTimeouts']]:
        return pulumi.get(self, "timeouts")

