# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetMqcloudApplicationResult',
    'AwaitableGetMqcloudApplicationResult',
    'get_mqcloud_application',
    'get_mqcloud_application_output',
]

@pulumi.output_type
class GetMqcloudApplicationResult:
    """
    A collection of values returned by getMqcloudApplication.
    """
    def __init__(__self__, applications=None, id=None, name=None, service_instance_guid=None):
        if applications and not isinstance(applications, list):
            raise TypeError("Expected argument 'applications' to be a list")
        pulumi.set(__self__, "applications", applications)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if service_instance_guid and not isinstance(service_instance_guid, str):
            raise TypeError("Expected argument 'service_instance_guid' to be a str")
        pulumi.set(__self__, "service_instance_guid", service_instance_guid)

    @_builtins.property
    @pulumi.getter
    def applications(self) -> Sequence['outputs.GetMqcloudApplicationApplicationResult']:
        return pulumi.get(self, "applications")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="serviceInstanceGuid")
    def service_instance_guid(self) -> _builtins.str:
        return pulumi.get(self, "service_instance_guid")


class AwaitableGetMqcloudApplicationResult(GetMqcloudApplicationResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetMqcloudApplicationResult(
            applications=self.applications,
            id=self.id,
            name=self.name,
            service_instance_guid=self.service_instance_guid)


def get_mqcloud_application(id: Optional[_builtins.str] = None,
                            name: Optional[_builtins.str] = None,
                            service_instance_guid: Optional[_builtins.str] = None,
                            opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetMqcloudApplicationResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    __args__['serviceInstanceGuid'] = service_instance_guid
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('ibm:index/getMqcloudApplication:getMqcloudApplication', __args__, opts=opts, typ=GetMqcloudApplicationResult, package_ref=_utilities.get_package()).value

    return AwaitableGetMqcloudApplicationResult(
        applications=pulumi.get(__ret__, 'applications'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        service_instance_guid=pulumi.get(__ret__, 'service_instance_guid'))
def get_mqcloud_application_output(id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                   name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                   service_instance_guid: Optional[pulumi.Input[_builtins.str]] = None,
                                   opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetMqcloudApplicationResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    __args__['serviceInstanceGuid'] = service_instance_guid
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('ibm:index/getMqcloudApplication:getMqcloudApplication', __args__, opts=opts, typ=GetMqcloudApplicationResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetMqcloudApplicationResult(
        applications=pulumi.get(__response__, 'applications'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        service_instance_guid=pulumi.get(__response__, 'service_instance_guid')))
