# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetIsOperatingSystemsResult',
    'AwaitableGetIsOperatingSystemsResult',
    'get_is_operating_systems',
    'get_is_operating_systems_output',
]

@pulumi.output_type
class GetIsOperatingSystemsResult:
    """
    A collection of values returned by getIsOperatingSystems.
    """
    def __init__(__self__, id=None, operating_systems=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if operating_systems and not isinstance(operating_systems, list):
            raise TypeError("Expected argument 'operating_systems' to be a list")
        pulumi.set(__self__, "operating_systems", operating_systems)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="operatingSystems")
    def operating_systems(self) -> Sequence['outputs.GetIsOperatingSystemsOperatingSystemResult']:
        return pulumi.get(self, "operating_systems")


class AwaitableGetIsOperatingSystemsResult(GetIsOperatingSystemsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetIsOperatingSystemsResult(
            id=self.id,
            operating_systems=self.operating_systems)


def get_is_operating_systems(id: Optional[_builtins.str] = None,
                             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetIsOperatingSystemsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('ibm:index/getIsOperatingSystems:getIsOperatingSystems', __args__, opts=opts, typ=GetIsOperatingSystemsResult, package_ref=_utilities.get_package()).value

    return AwaitableGetIsOperatingSystemsResult(
        id=pulumi.get(__ret__, 'id'),
        operating_systems=pulumi.get(__ret__, 'operating_systems'))
def get_is_operating_systems_output(id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetIsOperatingSystemsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('ibm:index/getIsOperatingSystems:getIsOperatingSystems', __args__, opts=opts, typ=GetIsOperatingSystemsResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetIsOperatingSystemsResult(
        id=pulumi.get(__response__, 'id'),
        operating_systems=pulumi.get(__response__, 'operating_systems')))
