# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetCisOriginPoolsResult',
    'AwaitableGetCisOriginPoolsResult',
    'get_cis_origin_pools',
    'get_cis_origin_pools_output',
]

@pulumi.output_type
class GetCisOriginPoolsResult:
    """
    A collection of values returned by getCisOriginPools.
    """
    def __init__(__self__, cis_id=None, cis_origin_pools=None, id=None, timeouts=None):
        if cis_id and not isinstance(cis_id, str):
            raise TypeError("Expected argument 'cis_id' to be a str")
        pulumi.set(__self__, "cis_id", cis_id)
        if cis_origin_pools and not isinstance(cis_origin_pools, list):
            raise TypeError("Expected argument 'cis_origin_pools' to be a list")
        pulumi.set(__self__, "cis_origin_pools", cis_origin_pools)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if timeouts and not isinstance(timeouts, dict):
            raise TypeError("Expected argument 'timeouts' to be a dict")
        pulumi.set(__self__, "timeouts", timeouts)

    @_builtins.property
    @pulumi.getter(name="cisId")
    def cis_id(self) -> _builtins.str:
        return pulumi.get(self, "cis_id")

    @_builtins.property
    @pulumi.getter(name="cisOriginPools")
    def cis_origin_pools(self) -> Sequence['outputs.GetCisOriginPoolsCisOriginPoolResult']:
        return pulumi.get(self, "cis_origin_pools")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def timeouts(self) -> Optional['outputs.GetCisOriginPoolsTimeoutsResult']:
        return pulumi.get(self, "timeouts")


class AwaitableGetCisOriginPoolsResult(GetCisOriginPoolsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetCisOriginPoolsResult(
            cis_id=self.cis_id,
            cis_origin_pools=self.cis_origin_pools,
            id=self.id,
            timeouts=self.timeouts)


def get_cis_origin_pools(cis_id: Optional[_builtins.str] = None,
                         id: Optional[_builtins.str] = None,
                         timeouts: Optional[Union['GetCisOriginPoolsTimeoutsArgs', 'GetCisOriginPoolsTimeoutsArgsDict']] = None,
                         opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetCisOriginPoolsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['cisId'] = cis_id
    __args__['id'] = id
    __args__['timeouts'] = timeouts
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('ibm:index/getCisOriginPools:getCisOriginPools', __args__, opts=opts, typ=GetCisOriginPoolsResult, package_ref=_utilities.get_package()).value

    return AwaitableGetCisOriginPoolsResult(
        cis_id=pulumi.get(__ret__, 'cis_id'),
        cis_origin_pools=pulumi.get(__ret__, 'cis_origin_pools'),
        id=pulumi.get(__ret__, 'id'),
        timeouts=pulumi.get(__ret__, 'timeouts'))
def get_cis_origin_pools_output(cis_id: Optional[pulumi.Input[_builtins.str]] = None,
                                id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                timeouts: Optional[pulumi.Input[Optional[Union['GetCisOriginPoolsTimeoutsArgs', 'GetCisOriginPoolsTimeoutsArgsDict']]]] = None,
                                opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetCisOriginPoolsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['cisId'] = cis_id
    __args__['id'] = id
    __args__['timeouts'] = timeouts
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('ibm:index/getCisOriginPools:getCisOriginPools', __args__, opts=opts, typ=GetCisOriginPoolsResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetCisOriginPoolsResult(
        cis_id=pulumi.get(__response__, 'cis_id'),
        cis_origin_pools=pulumi.get(__response__, 'cis_origin_pools'),
        id=pulumi.get(__response__, 'id'),
        timeouts=pulumi.get(__response__, 'timeouts')))
