# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetBackupRecoveryAgentUpgradeTasksResult',
    'AwaitableGetBackupRecoveryAgentUpgradeTasksResult',
    'get_backup_recovery_agent_upgrade_tasks',
    'get_backup_recovery_agent_upgrade_tasks_output',
]

@pulumi.output_type
class GetBackupRecoveryAgentUpgradeTasksResult:
    """
    A collection of values returned by getBackupRecoveryAgentUpgradeTasks.
    """
    def __init__(__self__, id=None, ids=None, tasks=None, x_ibm_tenant_id=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if ids and not isinstance(ids, list):
            raise TypeError("Expected argument 'ids' to be a list")
        pulumi.set(__self__, "ids", ids)
        if tasks and not isinstance(tasks, list):
            raise TypeError("Expected argument 'tasks' to be a list")
        pulumi.set(__self__, "tasks", tasks)
        if x_ibm_tenant_id and not isinstance(x_ibm_tenant_id, str):
            raise TypeError("Expected argument 'x_ibm_tenant_id' to be a str")
        pulumi.set(__self__, "x_ibm_tenant_id", x_ibm_tenant_id)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def ids(self) -> Optional[Sequence[_builtins.float]]:
        return pulumi.get(self, "ids")

    @_builtins.property
    @pulumi.getter
    def tasks(self) -> Sequence['outputs.GetBackupRecoveryAgentUpgradeTasksTaskResult']:
        return pulumi.get(self, "tasks")

    @_builtins.property
    @pulumi.getter(name="xIbmTenantId")
    def x_ibm_tenant_id(self) -> _builtins.str:
        return pulumi.get(self, "x_ibm_tenant_id")


class AwaitableGetBackupRecoveryAgentUpgradeTasksResult(GetBackupRecoveryAgentUpgradeTasksResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetBackupRecoveryAgentUpgradeTasksResult(
            id=self.id,
            ids=self.ids,
            tasks=self.tasks,
            x_ibm_tenant_id=self.x_ibm_tenant_id)


def get_backup_recovery_agent_upgrade_tasks(id: Optional[_builtins.str] = None,
                                            ids: Optional[Sequence[_builtins.float]] = None,
                                            x_ibm_tenant_id: Optional[_builtins.str] = None,
                                            opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetBackupRecoveryAgentUpgradeTasksResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['ids'] = ids
    __args__['xIbmTenantId'] = x_ibm_tenant_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('ibm:index/getBackupRecoveryAgentUpgradeTasks:getBackupRecoveryAgentUpgradeTasks', __args__, opts=opts, typ=GetBackupRecoveryAgentUpgradeTasksResult, package_ref=_utilities.get_package()).value

    return AwaitableGetBackupRecoveryAgentUpgradeTasksResult(
        id=pulumi.get(__ret__, 'id'),
        ids=pulumi.get(__ret__, 'ids'),
        tasks=pulumi.get(__ret__, 'tasks'),
        x_ibm_tenant_id=pulumi.get(__ret__, 'x_ibm_tenant_id'))
def get_backup_recovery_agent_upgrade_tasks_output(id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                                   ids: Optional[pulumi.Input[Optional[Sequence[_builtins.float]]]] = None,
                                                   x_ibm_tenant_id: Optional[pulumi.Input[_builtins.str]] = None,
                                                   opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetBackupRecoveryAgentUpgradeTasksResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['ids'] = ids
    __args__['xIbmTenantId'] = x_ibm_tenant_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('ibm:index/getBackupRecoveryAgentUpgradeTasks:getBackupRecoveryAgentUpgradeTasks', __args__, opts=opts, typ=GetBackupRecoveryAgentUpgradeTasksResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetBackupRecoveryAgentUpgradeTasksResult(
        id=pulumi.get(__response__, 'id'),
        ids=pulumi.get(__response__, 'ids'),
        tasks=pulumi.get(__response__, 'tasks'),
        x_ibm_tenant_id=pulumi.get(__response__, 'x_ibm_tenant_id')))
