# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetIsInstanceNetworkInterfacesResult',
    'AwaitableGetIsInstanceNetworkInterfacesResult',
    'get_is_instance_network_interfaces',
    'get_is_instance_network_interfaces_output',
]

@pulumi.output_type
class GetIsInstanceNetworkInterfacesResult:
    """
    A collection of values returned by getIsInstanceNetworkInterfaces.
    """
    def __init__(__self__, id=None, instance_name=None, network_interfaces=None, total_count=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if instance_name and not isinstance(instance_name, str):
            raise TypeError("Expected argument 'instance_name' to be a str")
        pulumi.set(__self__, "instance_name", instance_name)
        if network_interfaces and not isinstance(network_interfaces, list):
            raise TypeError("Expected argument 'network_interfaces' to be a list")
        pulumi.set(__self__, "network_interfaces", network_interfaces)
        if total_count and not isinstance(total_count, float):
            raise TypeError("Expected argument 'total_count' to be a float")
        pulumi.set(__self__, "total_count", total_count)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="instanceName")
    def instance_name(self) -> _builtins.str:
        return pulumi.get(self, "instance_name")

    @_builtins.property
    @pulumi.getter(name="networkInterfaces")
    def network_interfaces(self) -> Sequence['outputs.GetIsInstanceNetworkInterfacesNetworkInterfaceResult']:
        return pulumi.get(self, "network_interfaces")

    @_builtins.property
    @pulumi.getter(name="totalCount")
    def total_count(self) -> _builtins.float:
        return pulumi.get(self, "total_count")


class AwaitableGetIsInstanceNetworkInterfacesResult(GetIsInstanceNetworkInterfacesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetIsInstanceNetworkInterfacesResult(
            id=self.id,
            instance_name=self.instance_name,
            network_interfaces=self.network_interfaces,
            total_count=self.total_count)


def get_is_instance_network_interfaces(id: Optional[_builtins.str] = None,
                                       instance_name: Optional[_builtins.str] = None,
                                       opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetIsInstanceNetworkInterfacesResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['instanceName'] = instance_name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('ibm:index/getIsInstanceNetworkInterfaces:getIsInstanceNetworkInterfaces', __args__, opts=opts, typ=GetIsInstanceNetworkInterfacesResult, package_ref=_utilities.get_package()).value

    return AwaitableGetIsInstanceNetworkInterfacesResult(
        id=pulumi.get(__ret__, 'id'),
        instance_name=pulumi.get(__ret__, 'instance_name'),
        network_interfaces=pulumi.get(__ret__, 'network_interfaces'),
        total_count=pulumi.get(__ret__, 'total_count'))
def get_is_instance_network_interfaces_output(id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                              instance_name: Optional[pulumi.Input[_builtins.str]] = None,
                                              opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetIsInstanceNetworkInterfacesResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['instanceName'] = instance_name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('ibm:index/getIsInstanceNetworkInterfaces:getIsInstanceNetworkInterfaces', __args__, opts=opts, typ=GetIsInstanceNetworkInterfacesResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetIsInstanceNetworkInterfacesResult(
        id=pulumi.get(__response__, 'id'),
        instance_name=pulumi.get(__response__, 'instance_name'),
        network_interfaces=pulumi.get(__response__, 'network_interfaces'),
        total_count=pulumi.get(__response__, 'total_count')))
