# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetIsNetworkAclsResult',
    'AwaitableGetIsNetworkAclsResult',
    'get_is_network_acls',
    'get_is_network_acls_output',
]

@pulumi.output_type
class GetIsNetworkAclsResult:
    """
    A collection of values returned by getIsNetworkAcls.
    """
    def __init__(__self__, id=None, network_acls=None, resource_group=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if network_acls and not isinstance(network_acls, list):
            raise TypeError("Expected argument 'network_acls' to be a list")
        pulumi.set(__self__, "network_acls", network_acls)
        if resource_group and not isinstance(resource_group, str):
            raise TypeError("Expected argument 'resource_group' to be a str")
        pulumi.set(__self__, "resource_group", resource_group)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="networkAcls")
    def network_acls(self) -> Sequence['outputs.GetIsNetworkAclsNetworkAclResult']:
        return pulumi.get(self, "network_acls")

    @_builtins.property
    @pulumi.getter(name="resourceGroup")
    def resource_group(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "resource_group")


class AwaitableGetIsNetworkAclsResult(GetIsNetworkAclsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetIsNetworkAclsResult(
            id=self.id,
            network_acls=self.network_acls,
            resource_group=self.resource_group)


def get_is_network_acls(id: Optional[_builtins.str] = None,
                        resource_group: Optional[_builtins.str] = None,
                        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetIsNetworkAclsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['resourceGroup'] = resource_group
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('ibm:index/getIsNetworkAcls:getIsNetworkAcls', __args__, opts=opts, typ=GetIsNetworkAclsResult, package_ref=_utilities.get_package()).value

    return AwaitableGetIsNetworkAclsResult(
        id=pulumi.get(__ret__, 'id'),
        network_acls=pulumi.get(__ret__, 'network_acls'),
        resource_group=pulumi.get(__ret__, 'resource_group'))
def get_is_network_acls_output(id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                               resource_group: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                               opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetIsNetworkAclsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['resourceGroup'] = resource_group
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('ibm:index/getIsNetworkAcls:getIsNetworkAcls', __args__, opts=opts, typ=GetIsNetworkAclsResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetIsNetworkAclsResult(
        id=pulumi.get(__response__, 'id'),
        network_acls=pulumi.get(__response__, 'network_acls'),
        resource_group=pulumi.get(__response__, 'resource_group')))
