# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['SccRuleAttachmentArgs', 'SccRuleAttachment']

@pulumi.input_type
class SccRuleAttachmentArgs:
    def __init__(__self__, *,
                 scc_rule_attachment_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a SccRuleAttachment resource.
        """
        if scc_rule_attachment_id is not None:
            pulumi.set(__self__, "scc_rule_attachment_id", scc_rule_attachment_id)

    @_builtins.property
    @pulumi.getter(name="sccRuleAttachmentId")
    def scc_rule_attachment_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "scc_rule_attachment_id")

    @scc_rule_attachment_id.setter
    def scc_rule_attachment_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "scc_rule_attachment_id", value)


@pulumi.input_type
class _SccRuleAttachmentState:
    def __init__(__self__, *,
                 scc_rule_attachment_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering SccRuleAttachment resources.
        """
        if scc_rule_attachment_id is not None:
            pulumi.set(__self__, "scc_rule_attachment_id", scc_rule_attachment_id)

    @_builtins.property
    @pulumi.getter(name="sccRuleAttachmentId")
    def scc_rule_attachment_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "scc_rule_attachment_id")

    @scc_rule_attachment_id.setter
    def scc_rule_attachment_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "scc_rule_attachment_id", value)


@pulumi.type_token("ibm:index/sccRuleAttachment:SccRuleAttachment")
class SccRuleAttachment(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 scc_rule_attachment_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a SccRuleAttachment resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[SccRuleAttachmentArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a SccRuleAttachment resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param SccRuleAttachmentArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SccRuleAttachmentArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 scc_rule_attachment_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SccRuleAttachmentArgs.__new__(SccRuleAttachmentArgs)

            __props__.__dict__["scc_rule_attachment_id"] = scc_rule_attachment_id
        super(SccRuleAttachment, __self__).__init__(
            'ibm:index/sccRuleAttachment:SccRuleAttachment',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            scc_rule_attachment_id: Optional[pulumi.Input[_builtins.str]] = None) -> 'SccRuleAttachment':
        """
        Get an existing SccRuleAttachment resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SccRuleAttachmentState.__new__(_SccRuleAttachmentState)

        __props__.__dict__["scc_rule_attachment_id"] = scc_rule_attachment_id
        return SccRuleAttachment(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="sccRuleAttachmentId")
    def scc_rule_attachment_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "scc_rule_attachment_id")

